### ISSUE TITLE
export encode/decode for types

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/rlp#10]
In RLPx context we need read code from message and then read content.
For example ping message: `<Buffer 02 c0>` if we trying decode with current implementation we get `AssertionError: invalid remainder`.
We can read only first byte and then decode content with RLP, it works, but only for message codes that less than 0x80.

Reading message code in [go-ethereum](https://github.com/ethereum/go-ethereum/blob/fc0638f9d86fe8c0917c82cf32f548bb1953bfe9/p2p/rlpx.go#L666).

**Comment by wanderer** [comment]
the api is `rlp.decode(encoded, [skipRemainderCheck=false])`  so just second parameter to true.

**Comment by fanatid** [comment]
@wanderer nice suggestion, but then we also should return number of decoded bytes (#9 should help us in this)

**Comment by wanderer** [comment]
I'm not sure why this would be a problem. Since you should always know the size of the packet. Based on it type. So for example auth is [307](https://github.com/ethereumjs/rlp/issues/10#issuecomment-219052283) and the header packet contains the [body size](https://github.com/ethereumjs/node-devp2p/blob/master/lib/peer.js#L153-L155). After you get the  you then can [slice the packet accordingly](https://github.com/ethereumjs/node-devp2p/blob/master/lib/peer.js#L84).  So you really shouldn't have to worry about remaineders

**Comment by holgerd77** [comment]
Explanation of possible solution and no further discussion for a long time, will close.
