### ISSUE TITLE
Reach 95%+ code coverage with tests

### ISSUE THREAD

**Issue by axic** [ethereumjs/rlp#21]

**Comment by axic** [comment]
It is only at 90% now :)

**Comment by holgerd77** [comment]
I didn't close, think this was GitHub. :-)

**Comment by holgerd77** [comment]
Would make sense to accompany this by some better structuring of the [dataTypes](https://github.com/ethereumjs/rlp/blob/master/test/dataTypes.spec.ts) tests, so that it becomes more apparent that the different type cases are tested in a systematic way.

There are also other inconsistencies in test names and descriptions which should be fixed along the way. Some more structuring comments might also be some way to get more oversight into the file.

**Comment by ryanio** [comment]
We are at 96% now thanks to @jochem-brouwer with #101 :)
