### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by axic** [ethereumjs/rlp#29]
Part of https://github.com/ethereumjs/organization/issues/28

**Comment by holgerd77** [comment]
Don't know, how best to tackle this? Should this also break with taking different types as input for generic ``encode`` and ``decode`` functionality, like also mirrored in the TypeScript interface PR https://github.com/ethereumjs/rlp/pull/25? Or do a breaking release with separate ``encodeString()``,... methods? Just allow ``Buffer`` values?

Any other possible strategies?

**Comment by whymarrh** [comment]
I think for starters (once #25 is merged) we can rewrite the project to produce that API. Once that's in place we can start updating the types. How do we feel about that?

**Comment by holgerd77** [comment]
You don't have to wait for #25 to be merged, this is not very much code and @ukstv was not responsive on this lately (mostly due to our fault since this took ages to go forward this so I wouldn't blame if he lost patience). But in doubt get in short contact on this, I am no TypeScript expert, so I also have separately the question if these separate definition files are still necessary if one is rewriting the whole library?

I am otherwise ok with the procedure, to keep the API on first iteration - if this keeps things easier - and then change on that later on.

**Comment by holgerd77** [comment]
@whymarrh Have sent you a message on Gitter, not sure, what is the best way to reach out to you? Anyhow, maybe respond there. :smile:

**Comment by whymarrh** [comment]
I think we can close this issue now that #37 has been merged 🎉
