### ISSUE TITLE
Question, why is decode(encode([0])) empty buffer?

### ISSUE THREAD

**Issue by syuhei176** [ethereumjs/rlp#40]
## Description

I wonder why decode(encode([0])) is empty buffer.

```
> RLP.decode(RLP.encode([0, 1, 2]))
[ <Buffer >, <Buffer 01>, <Buffer 02> ]
```

**Comment by holgerd77** [comment]
This is an open bug and we have to examine further. This was also raised here https://github.com/ethereumjs/rlp/issues/28, I know adopted the issue title on this because it wasn't obvious before, will close this issue.

We definitely have to dig deeper into this, feel very free to join discussion and add to investigation on the issue I mentioned above.
